secretkeylabs/xverse-core

transactions/btc.ts

This PR is related to https://github.com/secretkeylabs/xverse-web-extension/pull/426

Add the BTC fees in sats per vB to the fees calculation func return value

---

transactions/stacking.ts

fixed function arguments for generate delegate transaction function call

Fix delegate tx function args

---

api/xverse.ts

Context: https://linear.app/xverseapp/issue/ENG-2245/add-brc-721e-support

Add BRC-721E support

---

.eslintrc.json
.github/workflows/build.yml
.prettierrc.json
package.json

- Set up linting and prettier configs to match other repos
- Added linting script
- Added linting placeholder in CI
In order to fix linting and code formatting and turn on the lint checks in the CI, we need to clean up our pending PRs in the repo to minimise conflicts.

chore: setup linting and prettier

---

api/xverse.ts
types/api/xverse/transaction.ts

Added the change for the app info API change that returns the fee thresholds. 
API change: https://github.com/secretkeylabs/xverse-api/pull/163

App info API change

---

api/stacks.ts
coins/index.ts
constant.ts
index.ts
types/api/stacks/assets.ts
types/api/xverse/coins.ts
types/index.ts

The PR adds a function to fetch metadata of coins using their contract. 
A list of supported coins is also added in order to identify supported coins

Add function to fetch coin metadata

---

package-lock.json
package.json

release
Release here:
https://github.com/secretkeylabs/xverse-core/releases/tag/v1.4.2

release 1.4.2

---

api/helper.ts
api/stacks.ts
package-lock.json
package.json
tests/api/helper.test.ts

Issue Link: https://linear.app/xverseapp/issue/ENG-2581/unit-test-and-fix-fetch-fetchpendingstxtransactions-function
Changes:
- fix logic in fetchStxPendingTransactions
- add unit tests
Impact:
- fetchStxPendingTransactions
- fetchStxAddressData (total_transactions)

Hotfix release/v1.5.1

---

constant.ts
tests/connect/createAuthResponse.test.ts

changing the gaia hub url
due to Hiro migrating their Gaia hub to a new provider and domain, we need to point to the new provider url 
Changes:
- gaia hub provider url
Impact:
- might have impact on account restoration until gaia is fully migrated

updated gaiahub url

---

package.json

Release
chore: use release published to trigger a release-package workflow by @teebszet in https://github.com/secretkeylabs/xverse-core/pull/208
feat: use xord for ordinal detection by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/203
fix internalPublicKey update with default by @m-aboelenein in https://github.com/secretkeylabs/xverse-core/pull/206

Release v1.6.1

---

api/helper.ts

original PR: https://github.com/secretkeylabs/xverse-core/pull/211

Remove check to not include ordinal address as recipient address

---

transactions/btc.utils.ts

fix: api path in getOrdinalsByAddress import

---

api/helper.ts
package.json

Release
chore: performance improvements for account derivation by @fedeerbes in https://github.com/secretkeylabs/xverse-core/pull/196
fix: Remove check to not include ordinal address as recipient address by @teebszet  
https://github.com/secretkeylabs/xverse-core/pull/222
fix: ordinals recover tx https://github.com/secretkeylabs/xverse-core/pull/218 by @abdulhaseeb4239 
revert: fix: ordinals recover tx https://github.com/secretkeylabs/xverse-core/pull/224

Release v1.6.4

---

package-lock.json
package.json

Changes:
Impact:
- What to test

Release v1.6.5

---

account/index.ts

Changes:
Impact:
- What to test

refactor restoreWalletWithAccounts

---

package.json

* fix: refactor  and improve bip322 tests, remove unused functions by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/231
* Pass service fee args to mint function by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/236

release v1.7.3

---

package.json

Changes:
Impact:
- What to test

Release v1.7.4

---

types/index.ts
types/mixpanel.ts

Issue Link: #[[ENG-2754](https://linear.app/xverseapp/issue/ENG-2754/build-analytics-tracking-for-web-extension)]
Changes:
- Added `AnalyticsEvents` enum containing mixpanel events that we're going to use for web extension (and then probably for mobile)
Impact:
- This PR should be merged before the one in the web extension: https://github.com/secretkeylabs/xverse-web-extension/pull/590/

Add enum for mixpanel events

---

package-lock.json
package.json

Release v1.7.5

---

package-lock.json
package.json

* feat: add Ordinal UTXO from Xverse API functions by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/246
https://github.com/secretkeylabs/xverse-core/releases/tag/v1.8.1

release: 1.8.1

---

package-lock.json
package.json

release: v1.8.2

---

types/api/xverse/ordinals.ts

To make the api changes introduced in PR https://github.com/secretkeylabs/xverse-core/pull/247
Changes:
Updates type for collectible api functions

Update type for collectible api function

---

package.json

* feat: add collectible api endpoints in core by @teebszet in https://github.com/secretkeylabs/xverse-core/pull/253
* Update getBrc20History function and utils by @Imamah-Zafar in https://github.com/secretkeylabs/xverse-core/pull/247

release v1.9.0

---

package-lock.json
package.json

release 1.9.1

---

package-lock.json
package.json

* Handle gaia hub migration by @m-aboelenein in https://github.com/secretkeylabs/xverse-core/pull/214
**Full Changelog**: https://github.com/secretkeylabs/xverse-core/compare/v2.0.0...v2.1.0

release v2.1.0

---

.github/workflows/create-release.yml

release workflow
Changes:
- chore: add the what's changed notes to a release PR description
- chore: fix the html url linking to the draft release

chore: update create release workflow with what changed description

---

stacksCollectible/index.ts
tests/stacks/stacksNfts.test.ts

Dusana has identified a discrepancy in the collection data when compared with gamma. Upon reviewing the issue, I discovered a logical error within the `getAllNftsContracts` function that needs to be addressed.
Issue Link: https://linear.app/xverseapp/issue/ENG-3175/fix-stacks-collections-logic-on-xverse-core
Changes:
- Modified `getAllNftsContracts` function to fix the logic
- add test for fetching stacks NFTs
Impact:
- `getNftCollections` function
- stacks NFTs collections tab 
- What to test:
We need to check if the collections data matches with marketplace on different addresses

fix: stacks NFTs collection

---

types/api/xverse/ordinals.ts

This PR adds the total_inscriptions prop to CollectionsList interface

chore: add total_inscriptions to CollectionsList interface

---

ledger/index.ts
ledger/psbt.ts

We would like to sign PSBTs with Ledger to enable marketplace purchases via our Ledger integration.
Changes:
- Add new function to sign PSBTs using ledger
Impact:
- We will need to update the extension to make use of this code and test there.

feat: Add ledger PSBT signing

---

.github/workflows/create-release-pr.yml
.github/workflows/create-release.yml

chore: add a sleep to add label step in create-release-pr.yml

---

api/helper.ts

This PR changes the url we use to fetch ipfs assets

chore: change ipfs url to improve reliability

---

api/esplora/esploraAPiProvider.ts
api/index.ts
api/ordinals/provider.ts
connect/index.ts
index.ts
ledger/index.ts
seedVault/index.ts
transactions/btc.ts
transactions/btc.utils.ts
transactions/index.ts
types/index.ts

https://linear.app/xverseapp/issue/ENG-3129/fix-all-non-exported-types-from-xverse-core
https://linear.app/xverseapp/issue/ENG-3327/fix-all-tsc-errors-on-web-extension
for https://github.com/secretkeylabs/xverse-web-extension/pull/685
Changes:
- mostly fixing the missing exports in the built dist
- some type fixes
Impact:
- can test on the extension PR

chore: type fixes

---

package-lock.json
package.json

* release: v5.0.0 by @github-actions in https://github.com/secretkeylabs/xverse-core/pull/304
* Fix chain rbf logic by @victorkirov in https://github.com/secretkeylabs/xverse-core/pull/300
**Full Changelog**: https://github.com/secretkeylabs/xverse-core/compare/v5.0.0...v5.1.0
Draft release: https://github.com/secretkeylabs/xverse-core/releases/tag/untagged-282c2fc2e24a76d7863d

release: v5.1.0 to develop

---

.github/workflows/publish-github-release.yml
scripts/create-release-pr.sh

chore: fix publish github release workflow permissions

---

transactions/rbf.ts

Just changing the default account type for RBF to software from ledger.
Changes:
- makes the fallback account type software instead of ledger

Make RBF default account type Software instead of ledger

---

.github/workflows/release-package.yml

Changes:
Impact:
- What to test

chore: some shell command fixes to release package worlflow

---

transactions/helper.ts
transactions/stx.ts

Changes:
Impact:
- What to test

fix: cap stx contract call fees

---

ledger/transaction.ts

Inscribed UTXOs weren't being filtered out when selecting UTXOs for payment in ledger.
Changes:
- The UTXO selection code was changed in Ledger ordinal recovery
Impact:
- Inscribed UTXOs will no longer be selected as inputs for ordinal recovery flow
- Needs a new Core version published and updated in the web extension

Don't spend ordinals in ledger recovery

---

tests/api/utxoCache.test.ts
tests/transactions/bitcoin/context.test.ts
transactions/bitcoin/actionProcessors.ts
transactions/bitcoin/context.ts
transactions/bitcoin/enhancedPsbt.ts
transactions/bitcoin/extendedUtxo.ts
transactions/bitcoin/index.ts
transactions/bitcoin/types.ts
transactions/bitcoin/utils.ts

Changes:
Impact:
- What to test

Bug fix/psbt parsing dummy inputs

---

transactions/rbf.ts

Changes:
Impact:
- What to test

bug-fix/rbf-support-custom-seed-handler

---

package-lock.json
package.json

chore: update scure btc-signer to 1.2.1

---

tests/utils/brc20.test.ts
utils/brc20.ts
utils/index.ts

move brc20 validation logic into core

refactor: move brc20 validation logic into core

---

tests/utils/brc20.test.ts
utils/brc20.ts

Fix dec prop check in deploy operation and add lim and dec to the return value

chore: improve deploy checks and add lim and dec params to the return value

---

transactions/stx.ts

Issue Link: #[[ENG-3536](https://linear.app/xverseapp/issue/ENG-3536/improve-toomuchchaining-error-message-when-broadcasting-stacks-tx)]
Changes:
Impact:
- What to test

Improve “TooMuchChaining” error message when broadcasting Stacks tx

---

connect/dappIcon.ts
connect/index.ts
connect/manifest.ts
tests/connect/manifest.test.ts

- Utility functions for extracting metadata from a web manifest file 

Added web manifest utils
