secretkeylabs/xverse-core

package-lock.json, wallet/index.ts
We need the option to create a mnemonic without creating a new wallet, so the functionality was extracted to its own function.
=> feat: extract mnemonic creation to separate function

package-lock.json, tests/btc/transactions.test.ts, transactions/btc.ts
`signOrdinalSendTransaction` function is updated to take the a list of the address ordinals utxo to filter them out from the unspent outputs used to construct the transfer tx
=> filter unspent outputs using ordinals utxos

transactions/btc.ts
in this previously merged PR https://github.com/secretkeylabs/xverse-core/pull/159 we added a change to the `signOrdinalSendTransaction` function to filter out all the `utxos` that includes ordinals that aren't being sent in the transaction.
the previous implementation relies on the `txid` when filtering the `utxos` which adds an edge-case where if you had another output in the same `tx` where an output that contains an ordinal is it was being filtered out
this change takes into account the output index when comparing utxos
=> filter ordinal utxos to consider output index

tests/btc/transactions.test.ts, transactions/btc.ts
The fee would be different every time we fetch unspent outputs and calculate the fee from TX size.
I have added the sorting of unspent outputs before selecting for a transaction, on the basis of block time. This fixes the inconsistent fee issue. 
The unit tests are updated with correct mocking data. 
```
// Sort UTXOs based on block time in ascending order
unspentOutputs.sort((a, b) => {
if (a.status.block_time && b.status.block_time) {
return a.status.block_time - b.status.block_time;
}
// Handle cases where block time is missing
return 0;
});
```
=> Fix incorrect BTC fee

constant.ts, package-lock.json
before change:
making 2 requests for each NFT (redirected from gamma.io -> stacks.gamma.io)
after change:
making 1 request for each NFT to stacks.gamma.io
=> chore: use proper stacks.gamma.io host

.github/workflows/build.yml, .github/workflows/release-pull-request.yml, package-lock.json
This adds a publish step to PR builds (or if action is run manually on any branch) which publishes a test build to the package repository with a version `<current_package_version>-<commit_short_sha>`.
=> feat: build and publish test version on PRs

ledger/index.ts, ledger/transaction.ts
The current implementation of BTC transaction functions in ledger did not support multiple recipients. 
The PR updates the ledger functions so a BTC transaction with more than one recipient can be sent 
I tried broadcasting a multiple recipient transaction with ledger for testing with the given code: 
https://mempool.space/tx/36c17ce49bc6ec2b09757276c11fb83241d1fd2756e4e42040aced2631db6799
=> Allow multiple btc recipients in ledger

tests/btc/transactions.test.ts, transactions/btc.ts
- added the filterutxos in the fee calculation for ordinal send to make sure ordinal UTXO is removed from UTXO set used for fees. 
- added a try-catch block in `signOrdinalSendTransaction` to catch and reject the promise. 
- updated test for `getBtcFeesForOrdinalSend` function
Change on apps: 
- we need to pass in an additional parameter addressOrdinalsUtxos added in `getBtcFeesForOrdinalSend` same as `signOrdinalSendTransaction`
=> Filter utxos in send ordinal get fee function

.github/workflows/release-pull-request.yml
We publish a beta package for testing Xverse-core PRs. Since fork PRs run in the context of the forked repo for security reasons, we cannot do this publish for forks. This fixes the fork check to disable the publish for fork PRs.
The previous behaviour would check if the target was our repo, so all it was doing was preventing the run on PRs of forks into any forked target. This one specifically prevents runs on PRs between repos.
Context Link (if applicable): ENG-2447
=> fix: don't run publish beta on fork PR

transactions/stx.ts, types/api/stacks/transaction.ts
The `UnsignedStacksTransation` type did not have a `sponsored` param which is needed for creating sponsored transactions.
Related fix on app for sponsored transactions:
https://github.com/secretkeylabs/xverse/pull/1136
Changes:
Added optional `sponsored` param to `UnsignedStacksTransation` type
Impact:
Fixes type error when building sponsored transactions.
=> Add the sponsored param back to stx transaction type

api/ordinals.ts
The logic for valid BRC-20 transfer was not correct
Issue Link: https://linear.app/xverseapp/issue/ENG-2503/fix-valid-brc-20-logic
Updated the function `isBrcTransferValid` logic. 
New logic: If the inscription output is equal to genesis_tx_id, it is a valid BRC-20 transfer.
Changes:
- modified function `isBrcTransferValid`
- No breaking change
Impact:
- fixes the BRC-20 transfer status 
- we need to test the status of the BRC20 transfer inscriptions. 
=> fix: valid brc20 transfer logic

api/ordinals/provider.ts, constant.ts
Hiro's indexer has a few issues. Some of the IDs are incorrect, Ordinals are assigned to incorrect owners, and it's often behind due to slow indexing.
We've brought up our own API, based on Ord, with the same interface in order to replace the Hiro API. This PR changes the endpoint used for inscription data to be our indexer primarily, and to fall back to Hiro's api if our indexer returns a 50X status code.
Further to this, the URl we retrieved ordinal content from was changed to our ord instance since Hiro's IDs are sometimes incorrect and they wouldn't have the content in the correct URL.
Issue Link: ENG-2478
Changes:
We now use Xord for inscription data and our own ord for image content
Impact:
- …
=> Switch to xord with fallback to hiro

api/btc.ts, api/esplora/esploraAPiProvider.ts
We need functions to fetch individual BTC and Ordinal transaction from txId. We fetch the transaction from transaction status screens to show the transaction detail after the tx is broadcasted successfully. 
Issue Link: https://linear.app/xverseapp/issue/ENG-2480/add-fetch-btc-and-ordinal-transaction-functions
Context Link (if applicable): https://linear.app/xverseapp/issue/ENG-2427/update-transaction-status-screens
added two functions in api/btc.ts. to fetch BTC and Ordinal transaction from txId. 
Changes:
- added functions in api/btc.ts
- no breaking change
Impact:
- adds functionality to fetch individual BTC and Ordinal transactions
- https://github.com/secretkeylabs/xverse/pull/1125 This PR from the mobile app repo depends on this change
- …
=> Fetch BTC transaction from txId

types/account.ts
This PR is related to https://github.com/secretkeylabs/xverse-web-extension/pull/524 as it introduces the new field `deviceAccountIndex` for `Account` interface
Issue Link: https://linear.app/xverseapp/issue/ENG-2343/add-ability-to-remove-connected-ledger-account
Changes:
- Added `deviceAccountIndex` field for `Account` interface
Impact:
- What to test
=> Add `deviceAccountIndex` field for `Account` interface

package-lock.json, tests/transactions/btc.data.ts, tests/transactions/btc.fixtures.ts, tests/transactions/btc.test.ts, tests/transactions/btc.util.test.ts, transactions/btc.ts, transactions/btc.utils.ts
Txn made using this logic with fee rate set to 12: https://mempool.space/tx/d008c4788cf50a43a59d4c9e81a6642570bc9081bb951496dac2e0b7490597e6
NOTE: The requested fee rate is slightly higher when using this for transactions from a taproot address as the resulting transaction is smaller. We can expand on this in the future if we use this for ordinal transfers or other transactions from the taproot address.
Currently, we naively select which UTXOs to use for a transaction by picking UTXOs from a list ordered by block time (oldest to newest). This does not always end up with the most efficient transaction in terms of fees and best UTXO use. There is also an issue in how we calculate fees with the UTXO selection in that we add a change output during …
=> feat: add logic for getting best UTXO combo for txn

api/xverseInscribe.ts, constant.ts, tests/transactions/brc20.test.ts, transactions/brc20.ts, transactions/btc.ts, transactions/index.ts, types/api/xverseInscribe/brc20.ts, types/api/xverseInscribe/index.ts, types/index.ts
This adds the calls to the Xverse inscribe api  to enable 1 step BRC20 transfers.
Issue Link: ENG-2391
Changes:
- Added calls to the inscribe service for brc20 transfer fee estimation, order creation and order execution.
- No breaking changes
Impact:
- With these endpoints we will be able to make 1-step brc20 transfers
=> feat: implement required calls to inscribe service for BRC20 transfer

transactions/btc.ts
We needed to move all the ordinals transactions logic to xverse-core. Including fetching and address UTXOs and getting the correct UTXO to send. 
Issue Link: https://linear.app/xverseapp/issue/ENG-2528/move-ordinal-transactions-logic-to-xverse-core
I have created new functions to wrap up the existing ones. I passed the ordinal inscription and `isRecover` boolean. and function fetches the addressUtxos from ordinalAddress and from btcAddress if it's a recover transaction. 
Changes:
- modified transactions/btc.ts file to add new functions for getting fees for ordinal send transactions and signing ordinal transactions. 
Impact:
- This will help keep the logic consistent across the app and extension. and future changes …
=> Ordinal transaction functions

.github/workflows/release-package.yml
Currently the workflow doesn't get triggered if I create a Draft first and then Publish it (in two steps)
Impact:
- CI only
=> chore: use release published to trigger a release-package workflow

constant.ts, tests/connect/createAuthResponse.test.ts
Reverts secretkeylabs/xverse-core#188
=> Revert "updated gaiahub url"

transactions/psbt.ts
update psbt with account publicKey 
testing a `psbt` with no provided `TapInternalPublicKey` for a taproot input resulted in the extension failing to sign the input 
Changes:
- updating the `psbt` with the account default `TapInternalPublicKey` is done using the correct method
Impact:
- developers will be able to skip adding the user's public key to taproot Inputs when creating a `psbt`
=> fix internalPublicKey update with default

api/helper.ts, tests/api/helper.test.ts, types/api/shared/transaction.ts
user reported extension crashing
Issue Link: https://linear.app/xverseapp/issue/ENG-2619/crash-on-loading
Changes:
- guard against read properties of undefined errors in stx helper function
Impact:
- called from web-extension when displaying STX transactions
- also opened a PR for mobile to use this function
=> fix: guard against read properties of undefined errors in stx helper function

api/ordinals.ts
Array.at was used in a function, but that syntax is not supported in React Native. This PR changes to using the alternative syntax.
Impact:
The getOrdinalIdFromUtxo was failing in the mobile app. This is used in BTC recovery, which is currently not working as a result.
=> fix: remove array.at usage as not supported in Native

tests/btc/transactions.test.ts, transactions/btc.ts
The recover ordinal flow was not working properly after the migration of ordinal transaction logic. 
Issue Link: https://linear.app/xverseapp/issue/ENG-2690/fix-ordinal-recover-logic
Changes:
- added a new function that fetches ordinals utxos in BTC address
- pass ordinals utxos to sign ordinals transaction function
Impact:
- Send Ordinal, Recover Ordinal
- We need to test this PR with following PRs on mobile and extension
https://github.com/secretkeylabs/xverse/pull/1165
https://github.com/secretkeylabs/xverse-web-extension/pull/552
=> fix: ordinals recover tx

tests/btc/transactions.test.ts, transactions/btc.ts
This reverts commit aeee8a58afdb354664575190e4530d9bec1a7c58.
=> Revert "fix: ordinals recover tx (#218)"

api/ordinals.ts, constant.ts, types/api/xverse/ordinals.ts, types/index.ts
Add Ordinal UTXO calls to Xverse API.
Changes:
- Add get bundles for address end point
- Add get single bundle end point
=> feat: add Ordinal UTXO from Xverse API functions

connect/bip322Signature.ts, package-lock.json, package.json
https://linear.app/xverseapp/issue/ENG-2983/testing-the-web-extension-0200-rc1
https://github.com/secretkeylabs/sats-connect-example/pull/13/files
Changes:
- update @scure/btc to 1.1.0 and fix the version
Impact:
- bip322 message signing
https://github.com/secretkeylabs/xverse-core/assets/6109710/aa3599a5-640a-46d4-95a9-ea178baa26dc
=> fix: update scure/btc to 1.1.0 to fix bip322 message signing

api/utxoCache.ts, hooks/brc20/useBrc20TransferExecute.ts, hooks/inscriptions/useInscriptionExecute.ts, tests/api/utxoCache.test.ts, tests/transactions/brc20.test.ts, tests/transactions/inscriptionMint.test.ts, transactions/brc20.ts, transactions/inscriptionMint.ts
With the seed vault changes, the inscription hooks need to get a function which returns the seed phrase instead of the direct seed phrase to minimize time spent in memory.
Changes:
- Mobile and the extension will need to pass in a getSeedPhrase function instead of a string to the inscription hooks
- The UTXO cache was also missing args in function calls. We should probably force branch updates on PRs.
Impact:
- This will need to be implemented in the extension and in mobile.
=> fix: change minting seed phrase to getter func (ENG-3124) + UTXO cache args

api/gamma.ts, api/stacks.ts, api/utxoCache.ts, api/xverse.ts, api/xverseInscribe.ts, gaia/walletConfig.ts, hooks/brc20/useBrc20TransferExecute.ts, hooks/inscriptions/useInscriptionExecute.ts, ledger/transaction.ts, tests/api/helper.test.ts, tests/transactions/brc20.test.ts, tests/transactions/btc.fixtures.ts, transactions/btcNetwork.ts, transactions/inscriptionMint.ts, transactions/stacking.ts, transactions/stx.ts, tsconfig.json, types/api/stacks/transaction.ts, types/api/xverseInscribe/brc20.ts, wallet/index.ts
We had type aliases set up in tsconfig which were not being post-processed after a build. These were causing typing issues in our consuming applications.
Changes:
- Path aliases were removed from tsconfig.ts. 
- Only the "type" alias was used, so all imports from 'type' were changed to relative imports
Impact:
- This has no functional affect, only typing. It should fix some typing issues in the mobile and extension repos.
=> fix: Import types via relative path and remove path aliases

api/stacks.ts, constant.ts, stacksCollectible/index.ts, types/index.ts
required for https://linear.app/xverseapp/issue/ENG-3145/add-bns-name-detail-page
Changes:
- use 10s timeout for nft holdings fetch
- supply bns contract id as collection id, so frontend can treat it the same to show contract id, name, etc.
- add some missing types
Impact:
- stx nft collectibles tab (bns collection and detail page)
- the 10s timeout for nft holdings means the nfts tab will show the API error message quicker (but should still retry with the react-query retries 3 times)
=> fix: add a full bns collection id for bns collectibles

stacksCollectible/index.ts
This PR adds the total_nfts prop to getNftCollections method
Issue Link: #[ENG-3223](https://linear.app/xverseapp/issue/ENG-3223/add-the-totalnfts-information-for-stacks-nft-response-in-core)
Changes:
- add total_nfts prop to getNftCollections method
=> feat: add total_nfts prop to getNftCollections response

api/stacks.ts, stacksCollectible/index.ts, tests/stacks/stacksNfts.test.ts
issue: https://linear.app/xverseapp/issue/ENG-3226/api-rate-limit-issue-with-stx-nfts-in-the-collectibles-ui-pr
Changes:
- fetch stx holdings at 200 per page instead of 150
Impact:
- reduce slightly the likelihood of rate limiting
=> fix: raise the holdings fetch limit to max at 200

ledger/transaction.ts, tests/btc/transactions.test.ts, transactions/btc.ts
When selecting UTXOs to spend, we always take the biggest one as highest priority. This is problematic if a big UTXO is affected by a dust attack as it would be used over and over without being confirmed, potentially resulting in a chain of transactions with length of 25, the maximum allowed by Bitcoin.
If another transaction is executed and the last UTXO from that chain is the biggest, we would try to spend it again, resulting in a 400 from the Bitcoin node when trying to broadcast the transaction due to the long chain. This would effectively block your wallet from making transactions as that UTXO will always be picked first.
Changes:
- The logic to select which UTXOs to spend is changed, prioritising …
=> fix: improve UTXO selection for spend

api/utxoCache.ts, stacksCollectible/index.ts, tests/stacks/stacksNfts.test.ts, types/api/stacks/assets.ts
issue: [eng-3268](https://linear.app/xverseapp/issue/ENG-3268/mitigate-hiro-api-is-returning-duplicate-holdings)
Changes:
- refactor: organize nfts function to be pure, and move bns collection assignment in
- feat: remove thumbnail_nfts
- feat: sort and unique all_nfts for each collection
- added tests
Impact:
before:
after:
=> feat: mitigate hiro api is returning duplicate holdings

types/currency.ts
Previously, xverse-core supported only to compute the conversion rates for USD, EUR, CAD, CNY, ARS, KRW, HKD, JPY, SGD, GBP, BRL, RUB. This PR extends the support to Swiss Francs. In fact, the xverse.app api for the mainnet as well as for the testnet support Swiss Francs already:
```bash
curl 'https://api-testnet.xverse.app/v1/prices/btc/CHF'
curl 'https://api-3.xverse.app/v1/prices/btc/CHF'
```
Changes:
- Changes were only made to `types/currency.ts `
Impact:
- Allows for other software, e.g., the xverse-web-extension,  to compute the Swiss Francs conversion rates.
=> Extend supported fiat currencies to include Swiss Franc (CHF)

api/ordinals.ts, api/ordinals/provider.ts
When making payments from payments address, we only pick UTXOs that don't have inscriptions on them. We check the UTXOs by making a call to the backend one at a time. This leads to rate limits being hit.
Changes:
- We get all the inscriptions for the address in batches and map them to the UTXOs instead
Impact:
- This fixes the rate limiting issue and should speed up the loading of the confirmation pages for users with many UTXOs in their payments address
=> fix: Get UTXO ordinal data in batches

api/ordinals.ts, api/utxoCache.ts, tests/api/ordinals.test.ts, types/api/xverse/ordinals.ts
This PR implements the v2 of exotics API and adds an util to map API response to Bundle
Changes:
- add v2 of exotics API with types (breaking change)
- add mapRareSatsAPIResponseToBundle and test (non breaking change)
=> chore: use exotics api v2

ledger/transaction.ts, tests/btc/transactions.test.ts, transactions/btc.ts, transactions/inscriptionMint.ts
We were using confirmed Dust UTXOs as inputs for txns before unconfirmed large UTXOs (e.g. change).
Additionally, we weren't filtering out unconfirmed UTXOs when selecting them for inscription commit txns, so the fee estimate logic was using different logic to the final commit txn build logic causing inconsistencies.
Changes:
- When selecting UTXOs, if a fee rate has not been specified, we use the regular fee rate to filter out dust UTXOs
Impact:
- We would no longer use dust UTXOs for txns
=> Don't use dust UTXOs in txns

account/index.ts, api/btc.ts, api/esplora/esploraAPiProvider.ts, api/ordinals.ts, api/xverse.ts, ledger/btc.ts, ledger/psbt.ts, ledger/transaction.ts, tests/btc/transactions.test.ts, tests/transactions/rbf.data.ts, tests/transactions/rbf.test.ts, transactions/brc20.ts, transactions/btc.ts, transactions/btc.utils.ts, transactions/rbf.ts
Currently, when changing the electrs URL in the apps, we don't use the custom URL for most functions. This ensures that all the places that use the URL have the api provider injected instead of being created in place, allowing the injection of a provider with a custom URL. 
Changes:
- All functions that created their own instance of the Esplora API Provider now accept it as an argument instead.
Impact:
- We will need to change the web extension and mobile apps to inject the provider in all the changed functions.
=> Use custom url for electrs api

api/ordinals.ts, package-lock.json, package.json, tests/api/ordinals.test.ts, types/error.ts
Changes:
fix: move critical logic for ignoring 404s into core
=> fix: provide a getOrdinalsInUtxos if found function

api/esplora/esploraAPiProvider.ts, api/esplora/types.ts
We should implement a function that retrieves payload data from the Bitcoin address data API. This will enable us to perform various calculations on the front-end, such as determining the balance of confirmed UTXOs.
Issue Link: [ENG-3385](https://linear.app/xverseapp/issue/ENG-3385/[ext-%F0%9F%8C%8D]-inform-users-that-they-dont-have-enough-confirmed-funds-to)
Changes:
- added function `getAddressData` in `esploraApiProvider.ts`
- no breaking changes
=> chore: add address data function in esplora provider

connect/transactionRequest.test.ts, connect/transactionRequest.ts
https://linear.app/xverseapp/issue/ENG-3458/stx-fees-are-not-being-estimated
Changes:
- move the apply fee multiplier function to core after merging in changes from stx tx hex signing
- add unit tests for fee multiplier/threshold logic
Impact:
- stx token transfers will have fees capped at the thresholdHighStacksFees amount
=> refactor: move the applyFeeMultipliers function to core

transactions/bitcoin/context.ts, transactions/bitcoin/enhancedPsbt.ts
TODO: Unit testing
The new PSBT logic ignored the inputs to sign arg from sats connect. It actually needs to process them in case of a multisig scenario where we cannot match the inputs witness script to the pub key.
Changes:
- The inputs to sign arg is no longer ignored
To test:
- Use this file in this branch in the sats-connect example app: https://github.com/secretkeylabs/sats-connect-example/blob/victor/aproot-example/src/components/taprootPsbt.tsx
- Try and go through the flow in that component
- The prior consolidated PSBT logic should fail while the new one should succeed
=> Add inputs to sign arg to PSBT logic

transactions/bitcoin/enhancedPsbt.ts
SigHash calcs were incorrect due to using bitwise OR instead of AND, resulting in the wrong data being shown on the extension PSBT signing screen.
=> fix bitwise ops

transactions/rbf.ts
We use the `getSeedPhrase` function to sign the transaction, so there is no need to ask for it in the RbfTransaction constructor, it would make more sense to pass it to the signing function. Also, this change would enable a better UX for the mobile app since we won't need to ask the user to enter a password when they just enter the Speed Up tx screen, instead, they'll have to enter the password only when they sign the RBF tx.
Issue Link: #[[ENG-3379](https://linear.app/xverseapp/issue/ENG-3379/make-ui-for-rbf-in-mobile-app)]
Changes:
- The breaking change here is that the `getSeedPhrase` function is now being passed to the `getReplacementTransaction` method of the …
=> Update the RbfTransaction class constructor

transactions/bitcoin/context.ts
Ledger requires bip32 derivation definition in order to know which inputs to sign. We add this into incoming PSBTs, but we don't remove it afterward, which causes an issue on Unisat as they use bitcoinlib-js which marks the input as an invalid taproot input as it has the field populated. 
Changes:
- The bip32 derivation is cleared after signing
Impact:
- This should fix listing on Unisat
- Requires an update on extension and mobile apps
=> Remove ledger fields from final PSBT

api/xverse.ts, types/api/xverse/coins.ts
Add a function to get the BRC-20 tokens data from Xverse API
Issue Link: https://linear.app/xverseapp/issue/ENG-3500/[tkn-1-mob📱]-☑️-control-brc-20-display-via-manage-tokens-screen
Changes:
- Added a new function in api/xverse.ts to get the BRC-20 tokens data from Xverse API
=> feat: get brc-20 tokens API

api/xverse.ts
Add a function to call spam tokens API
Issue Link: https://linear.app/xverseapp/issue/ENG-3680/add-spam-tokens-api-xverse-core
Changes:
- Just added a function to call the spam tokens API
- No breaking changes
=> feat: spam tokens API function

transactions/bitcoin/enhancedPsbt.ts
We were incorrectly detecting if a PSBT is sighash all or not.
Changes:
- Calculation of PSBT sighash
impact:
- This requires a new version of core and an update into the extension and mobile.
- The sign PSBT screen should show incoming inscriptions on marketplaces
=> Refactor sighash all calc for PSBTs

transactions/bitcoin/context.ts
Ledger requires nonWitnessUtxo to be set for segwit inputs in order to not display the non-verified input warning message. However, adding the value results in a PSBT with a slightly different structure, which some integrating apps don't like and they reject the signed PSBT.
Changes:
- We now only inject the nonWitnessUtxo value when manually adding inputs into transactions. This means that we won't add it when signing external PSBTs.
Impact:
- This should allow you to purchase from marketplaces again
=> Remove nonwitnessutxo injection on pre-sign input preparation

.eslintrc.json, api/gamma.ts, api/ordinals.ts, api/stacks.ts
I noticed that we currently don't have the `@typescript-eslint/no-unused-vars` eslint rule enabled and that we still have the hardcoded the request timeout value instead of using the constant, so this PR is here to address those things.
Changes:
- This PR enables the `@typescript-eslint/no-unused-vars` eslint rule to show the warnings for the unused vars/imports
- It also changes the requests timeout value from `30000` to `API_TIMEOUT_MILLI` constant which has the same value
Impact:
- This PR doesn't change any logic, it only improves the codebase and developer experience
=> Make some small refactoring related to variables

package-lock.json, package.json, transactions/stacking.ts
- Bugfix
This PR fixes an issue where address changed their format when converting to tuple 
Issue Link: #[ENG-3841](https://linear.app/xverseapp/issue/ENG-3841/wrong-reward-address-after-user-submit-the-delegation-tx)
Changes:
- use poxAddressToTuple from @stacks/stacking and add deprecate tag to addressToVersionHashbyteTupleCV
Impact:
- generation of unsigned delegation tx
=> fix: use stacks poxAddressToTuple instead of custom mapping to convert address to tuple
